### PR TITLE
generate device for user

### LINKED ISSUE #7: [3 XP] Implement Authentication [Nadya]
- [ ] Setup devise
- [ ] set up authentication with required gem

### PR DESCRIPTION
**Pull request by petushka1**
## Authentification

- [x] install devise
- [x] generate devise for User model

### CODE REVIEW

**Review by Theophileaseh — CHANGES_REQUESTED** [review]
Hi @petushka1 
## Changes Requested ♻️ 

Great work on implementing some of the project requirements.
There are still somethings you need to do:

- Add functionality to authenticate users using a token generated after login ⭐ 

Happy Coding 💻

**Comment by petushka1** [comment]
Thank you for your input. I opened a new branch to work on this. Completed setup. ref: 
https://whatraghulearned.wordpress.com/2019/07/15/add-devise_token_auth-to-an-existing-rails-app/
Please take a look:
https://github.com/Theophileaseh/Doctor-Appointment-Back-end/tree/auth-token

**Comment by Theophileaseh** [comment]
Hi @petushka1, you don't need to open a new branch for this. Do it on this branch so it can be reviewed and approved.

**Comment by petushka1** [comment]
@Theophileaseh Kindly take a look at changes made and thank you for your help and assistance with Auth token setup

**Review by Theophileaseh — APPROVED** [review]
Hi @petushka1 
## Approved 🎁 
Great work on implementing all project requirements
There is nothing else to say than merge.

**Pull request merged**
